create schema if not exists agentic_delivery;

revoke all on schema agentic_delivery from public, anon, authenticated;
grant usage on schema agentic_delivery to service_role;

create table agentic_delivery.deliveries (
  id bigint generated by default as identity primary key,
  code text not null,
  title text not null,
  objective text not null,
  status text not null default 'discovery',
  created_at timestamptz not null default now()
);

alter table agentic_delivery.deliveries enable row level security;

revoke all on table agentic_delivery.deliveries from anon, authenticated;
revoke all on sequence agentic_delivery.deliveries_id_seq from anon, authenticated;

grant select, insert, update, delete on table agentic_delivery.deliveries to service_role;
grant usage, select on sequence agentic_delivery.deliveries_id_seq to service_role;

comment on table agentic_delivery.deliveries is
  'Technology deliveries persisted by the server-side control plane. No browser role has direct access.';
